name: MinecraftSocial
version: '${project.version}'
main: nicholas.minecraftsocial.MinecraftSocial
api-version: '1.20'
commands:
  friend:
    description: Main command for friend operations
    usage: /friend help
  profile:
    description: Opens player's profile
    usage: /profile
#  debugFriendList:
#    description: Debug command to view friend list
#    usage: /debugFriendList {add/remove} {amount}

